/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdlib.h>
#include "stm32f407xx.h"

int main(void)
{
	Gpio::PinConfig intPinConf(PIN_1, INT_FT, PULL_UP, NO_AF);
	Gpio::PinConfig outputPinConf(PIN_15, OUTPUT);
	Gpio::Handler_t intHandler(GPIOA, &intPinConf);
	Gpio::Handler_t outputHandler(GPIOD, &outputPinConf);
	Gpio::Init(&intHandler);
	Gpio::Init(&outputHandler);

	Gpio::WriteToOutputPin(GPIOD, PIN_15, SET);

	while(1)
	{

	}
}

void delay(uint32_t ticks)
{
	for(size_t i = 0; i < (ticks * 1000); i++);
}

extern "C" void EXTI1_IRQHandler(void)
{
	BLUE_TOGGLE();
	if(EXTI->PR |= 1 << PIN_1)
	{
		CLR_EXTI_INT(PIN_1);
	}
}
