/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f407xx.h"

int main(void)
{
	Gpio::PinConfig inputPinConf(PIN_0, INPUT, INT_RFT);
	Gpio::PinConfig outputPinConf(PIN_15, OUTPUT, NONE);
	Gpio::Handler_t inputHandler(GPIOD, &inputPinConf);
	Gpio::Handler_t outputHandler(GPIOD, &outputPinConf);
	Gpio::Init(&inputHandler);
	Gpio::Init(&outputHandler);


	while(1)
	{
		uint8_t stat = Gpio::ReadFromInputPin(GPIOD, PIN_1);
		if(stat)
			Gpio::WriteToOutputPin(outputHandler.pGPIOx, PIN_15, SET);
		else
			Gpio::WriteToOutputPin(outputHandler.pGPIOx, PIN_15, RESET);
	}
}

extern "C" void EXTI0_IRQHandler(void)
{
	while(1);
}
