/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f407xx.h"

int main(void)
{
	GPIO_PinConfig pinConf(15);
	GPIO_Handle_t handler(GPIOD, &pinConf);
	Gpio::GPIO_Init(&handler);

	Gpio::GPIO_WriteToOutputPin(handler.pGPIOx, 15, SET);
    /* Loop forever */
	for(;;);
}
